// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7N2SoBaQcdFMRWjiMg96Z2yjEZmYDcR4',
    appId: '1:751884798882:web:eafd09daebaa93dac1c0fb',
    messagingSenderId: '751884798882',
    projectId: 'loja-57acb',
    authDomain: 'loja-57acb.firebaseapp.com',
    storageBucket: 'loja-57acb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmgiKK5uUfyupAjbfmvttoNQWR46hrvN0',
    appId: '1:751884798882:android:c9f4b07f0a651160c1c0fb',
    messagingSenderId: '751884798882',
    projectId: 'loja-57acb',
    storageBucket: 'loja-57acb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3-KtErmcv32YJQg_m0xLw2TkU3rBno1o',
    appId: '1:751884798882:ios:55c044716edeb92ac1c0fb',
    messagingSenderId: '751884798882',
    projectId: 'loja-57acb',
    storageBucket: 'loja-57acb.appspot.com',
    iosClientId: '751884798882-r8pketru1orol99jsn987g75gcda6q15.apps.googleusercontent.com',
    iosBundleId: 'com.example.findme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3-KtErmcv32YJQg_m0xLw2TkU3rBno1o',
    appId: '1:751884798882:ios:55c044716edeb92ac1c0fb',
    messagingSenderId: '751884798882',
    projectId: 'loja-57acb',
    storageBucket: 'loja-57acb.appspot.com',
    iosClientId: '751884798882-r8pketru1orol99jsn987g75gcda6q15.apps.googleusercontent.com',
    iosBundleId: 'com.example.findme',
  );
}
